In [23]:
import pandas as pd

In [24]:
melbourne_file_path = './melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path) 
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [25]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [26]:
melbourne_data = melbourne_data.dropna(axis=0)

In [27]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,6196.000000,6.196000e+03,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000
mean,2.931407,1.068828e+06,9.751097,3101.947708,2.902034,1.576340,1.573596,471.006940,141.568645,1964.081988,-37.807904,144.990201,7435.489509
std,0.971079,6.751564e+05,5.612065,86.421604,0.970055,0.711362,0.929947,897.449881,90.834824,38.105673,0.075850,0.099165,4337.698917
min,1.000000,1.310000e+05,0.000000,3000.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1196.000000,-38.164920,144.542370,389.000000
25%,2.000000,6.200000e+05,5.900000,3044.000000,2.000000,1.000000,1.000000,152.000000,91.000000,1940.000000,-37.855438,144.926198,4383.750000
50%,3.000000,8.800000e+05,9.000000,3081.000000,3.000000,1.000000,1.000000,373.000000,124.000000,1970.000000,-37.802250,144.995800,6567.000000
75%,4.000000,1.325000e+06,12.400000,3147.000000,3.000000,2.000000,2.000000,628.000000,170.000000,2000.000000,-37.758200,145.052700,10175.000000
max,8.000000,9.000000e+06,47.400000,3977.000000,9.000000,8.000000,10.000000,37000.000000,3112.000000,2018.000000,-37.457090,145.526350,21650.000000

In [28]:
y = melbourne_data.Price

In [10]:
y

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
9        1097000.0
11       1350000.0
12        750000.0
15       1310000.0
16       1200000.0
17       1176500.0
19        890000.0
20       1330000.0
23        500000.0
24       1100000.0
25       1315000.0
27       1447500.0
29       1135000.0
32       1290000.0
33        470000.0
34       1180000.0
35       1195000.0
36       1012500.0
37       1030000.0
38        840000.0
39        730000.0
40        770000.0
41        603000.0
42        700000.0
43        600000.0
           ...
12154     880000.0
12156     945000.0
12157     730000.0
12159     980000.0
12164     570000.0
12168     600000.0
12169     360000.0
12171     475000.0
12172     495000.0
12173     695000.0
12174     760000.0
12175     583500.0
12177     585000.0
12180    1245000.0
12181    2000000.0
12183     407000.0
12186     891000.0
12187     615500.0
12188     300000.0
12192    1310000.0
12197     645000.0
12198     482500.0
12199     394000.0
12202     821000.0
12203     635000.0
12205     601000.0
12206    1050000.0
12207     385000.0
12209     560000.0
12212    2450000.0
Name: Price, Length: 6196, dtype: float64

In [29]:
y.mean()

1068828.202065849

In [30]:
round(y.mean())

1068828

In [13]:
# this is where we select the features from the entire dataset

In [31]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [32]:
melbourne_features

['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [33]:
X=melbourne_data[melbourne_features]

In [34]:
X

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
4          4       1.0     120.0  -37.80720   144.99410
6          3       2.0     245.0  -37.80240   144.99930
7          2       1.0     256.0  -37.80600   144.99540
9          2       1.0     220.0  -37.80100   144.99890
11         3       2.0     214.0  -37.80850   144.99640
12         2       2.0       0.0  -37.80780   144.99650
15         2       1.0     238.0  -37.80900   144.99760
16         3       2.0     113.0  -37.80560   144.99300
17         3       1.0     138.0  -37.80210   144.99650
19         2       1.0     150.0  -37.80110   145.00040
20         4       2.0     780.0  -37.80730   144.99520
23         2       1.0       0.0  -37.80150   144.99720
24         2       2.0     124.0  -37.80790   144.99770
25         2       1.0     147.0  -37.80800   144.99400
27         3       3.0     166.0  -37.80170   145.00010
29         2       2.0      98.0  -37.80050   144.99520
32         3       1.0     168.0  -37.80070   144.99580
33         1       1.0       0.0  -37.80550   144.99610
34         2       1.0     162.0  -37.80160   144.99560
35         3       2.0     120.0  -37.80220   144.99540
36         2       1.0     182.0  -37.80210   144.99760
37         2       1.0     172.0  -37.80860   144.99460
38         3       2.0     303.0  -37.71800   144.87800
39         3       2.0       0.0  -37.72030   144.87550
40         3       2.0       0.0  -37.72030   144.87550
41         2       1.0     272.0  -37.72940   144.88800
42         3       2.0     239.0  -37.72180   144.88370
43         3       1.0     290.0  -37.72730   144.87440
...      ...       ...       ...        ...         ...
12154      4       2.0     535.0  -38.09683   145.12981
12156      2       1.0     126.0  -37.80473   144.89095
12157      3       2.0     340.0  -37.83172   144.86683
12159      2       1.0      64.0  -37.83326   144.95464
12164      2       1.0       0.0  -37.84679   145.00206
12168      2       1.0       0.0  -37.85911   144.97900
12169      2       1.0     143.0  -37.57063   144.70693
12171      3       1.0     754.0  -37.58442   144.75565
12172      3       2.0     563.0  -37.57499   144.75329
12173      3       1.0     694.0  -37.78871   144.81369
12174      3       1.0    1143.0  -37.79135   144.79948
12175      3       1.0     672.0  -37.80118   144.80996
12177      3       2.0     662.0  -37.70525   144.75699
12180      3       2.0     779.0  -37.76311   145.10494
12181      6       3.0    1054.0  -37.77404   145.11703
12183      2       1.0     140.0  -37.68199   145.01744
12186      3       2.0     199.0  -37.75948   144.99615
12187      3       2.0     238.0  -37.70322   144.88236
12188      2       1.0       0.0  -37.69815   144.88019
12192      5       3.0     818.0  -37.87846   145.24212
12197      4       2.0     555.0  -37.89359   144.66911
12198      4       2.0     533.0  -37.89337   144.64003
12199      3       2.0     287.0  -37.87895   144.67070
12202      4       3.0     544.0  -37.67841   144.87924
12203      3       2.0     691.0  -37.68026   144.88468
12205      3       2.0     972.0  -37.51232   145.13282
12206      3       1.0     179.0  -37.86558   144.90474
12207      1       1.0       0.0  -37.85588   144.89936
12209      2       1.0       0.0  -37.85581   144.99025
12212      6       3.0    1087.0  -37.81038   144.89389

[6196 rows x 5 columns]

In [35]:
X

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
4          4       1.0     120.0  -37.80720   144.99410
6          3       2.0     245.0  -37.80240   144.99930
7          2       1.0     256.0  -37.80600   144.99540
9          2       1.0     220.0  -37.80100   144.99890
11         3       2.0     214.0  -37.80850   144.99640
12         2       2.0       0.0  -37.80780   144.99650
15         2       1.0     238.0  -37.80900   144.99760
16         3       2.0     113.0  -37.80560   144.99300
17         3       1.0     138.0  -37.80210   144.99650
19         2       1.0     150.0  -37.80110   145.00040
20         4       2.0     780.0  -37.80730   144.99520
23         2       1.0       0.0  -37.80150   144.99720
24         2       2.0     124.0  -37.80790   144.99770
25         2       1.0     147.0  -37.80800   144.99400
27         3       3.0     166.0  -37.80170   145.00010
29         2       2.0      98.0  -37.80050   144.99520
32         3       1.0     168.0  -37.80070   144.99580
33         1       1.0       0.0  -37.80550   144.99610
34         2       1.0     162.0  -37.80160   144.99560
35         3       2.0     120.0  -37.80220   144.99540
36         2       1.0     182.0  -37.80210   144.99760
37         2       1.0     172.0  -37.80860   144.99460
38         3       2.0     303.0  -37.71800   144.87800
39         3       2.0       0.0  -37.72030   144.87550
40         3       2.0       0.0  -37.72030   144.87550
41         2       1.0     272.0  -37.72940   144.88800
42         3       2.0     239.0  -37.72180   144.88370
43         3       1.0     290.0  -37.72730   144.87440
...      ...       ...       ...        ...         ...
12154      4       2.0     535.0  -38.09683   145.12981
12156      2       1.0     126.0  -37.80473   144.89095
12157      3       2.0     340.0  -37.83172   144.86683
12159      2       1.0      64.0  -37.83326   144.95464
12164      2       1.0       0.0  -37.84679   145.00206
12168      2       1.0       0.0  -37.85911   144.97900
12169      2       1.0     143.0  -37.57063   144.70693
12171      3       1.0     754.0  -37.58442   144.75565
12172      3       2.0     563.0  -37.57499   144.75329
12173      3       1.0     694.0  -37.78871   144.81369
12174      3       1.0    1143.0  -37.79135   144.79948
12175      3       1.0     672.0  -37.80118   144.80996
12177      3       2.0     662.0  -37.70525   144.75699
12180      3       2.0     779.0  -37.76311   145.10494
12181      6       3.0    1054.0  -37.77404   145.11703
12183      2       1.0     140.0  -37.68199   145.01744
12186      3       2.0     199.0  -37.75948   144.99615
12187      3       2.0     238.0  -37.70322   144.88236
12188      2       1.0       0.0  -37.69815   144.88019
12192      5       3.0     818.0  -37.87846   145.24212
12197      4       2.0     555.0  -37.89359   144.66911
12198      4       2.0     533.0  -37.89337   144.64003
12199      3       2.0     287.0  -37.87895   144.67070
12202      4       3.0     544.0  -37.67841   144.87924
12203      3       2.0     691.0  -37.68026   144.88468
12205      3       2.0     972.0  -37.51232   145.13282
12206      3       1.0     179.0  -37.86558   144.90474
12207      1       1.0       0.0  -37.85588   144.89936
12209      2       1.0       0.0  -37.85581   144.99025
12212      6       3.0    1087.0  -37.81038   144.89389

[6196 rows x 5 columns]

In [36]:
avg_no_of_rooms=round(X['Rooms'].mean())

In [37]:
avg_no_of_rooms

3

In [38]:
avg_no_of_bathrooms=round(X['Bathroom'].mean())

In [39]:
avg_no_of_bathrooms

2

In [40]:
X.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

In [41]:
X.head()

   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

In [42]:
from sklearn.tree import DecisionTreeRegressor

In [43]:
melbourne_model = DecisionTreeRegressor(random_state=1)

In [44]:
melbourne_model.fit(X, y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=1, splitter='best')

In [45]:
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]

In [46]:
from sklearn.metrics import mean_absolute_error

In [47]:
predicted_home_prices = melbourne_model.predict(X)

In [48]:
mean_absolute_error(y, predicted_home_prices)

1115.7467183128902

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

In [51]:
train_X

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
10385      3       1.0     206.0  -37.87107   145.04991
5805       2       1.0       0.0  -37.85900   144.97670
8488       2       1.0    2701.0  -37.81090   144.86840
6672       3       1.0     670.0  -37.81340   144.87450
776        6       3.0     708.0  -37.91810   145.04400
1637       3       1.0     459.0  -37.82650   145.07200
5991       3       1.0     563.0  -37.79560   144.82600
10582      4       5.0     638.0  -38.06830   145.33833
1352       3       1.0     264.0  -37.76030   144.95730
8732       3       2.0     226.0  -37.79495   145.08192
7736       2       1.0     158.0  -37.79250   144.99950
4365       1       1.0       0.0  -37.80200   144.95160
8581       2       1.0     780.0  -37.82410   144.84190
10690      3       1.0     626.0  -37.71425   144.95013
5239       3       1.0     602.0  -37.71150   145.00090
10741      3       2.0     586.0  -37.67831   144.57342
8613       2       2.0      81.0  -37.79760   144.97780
5342       2       1.0     139.0  -37.81180   144.99370
7285       3       2.0     605.0  -37.77920   144.81170
419        3       1.0     792.0  -37.86400   145.09720
2710       2       1.0     253.0  -37.79680   144.88870
7424       3       2.0     236.0  -37.89820   145.01210
9631       4       2.0     612.0  -37.65478   145.05199
5864       4       2.0     436.0  -37.86290   144.98870
3403       2       2.0     124.0  -37.76180   145.02870
1212       2       1.0     604.0  -37.92680   145.00940
10252      3       2.0     553.0  -37.64463   145.04155
6074       3       1.0     696.0  -37.78360   144.79880
1459       4       3.0     499.0  -37.75380   144.94400
3996       2       1.0       0.0  -37.81060   144.96460
...      ...       ...       ...        ...         ...
1391       2       1.0       0.0  -37.76800   144.94080
3648       3       2.0    1353.0  -37.80060   145.02180
168        3       1.0     606.0  -37.86080   144.81240
4531       3       2.0     790.0  -37.71800   144.91240
3396       5       3.0    1006.0  -37.77650   145.04270
3719       2       1.0    1972.0  -37.78630   144.87690
9323       3       2.0     492.0  -37.64215   145.08584
9845       4       2.0     441.0  -37.73572   144.97256
3948       2       2.0       0.0  -37.78530   144.89990
11866      4       2.0     240.0  -37.85414   144.89561
5301       1       1.0    3516.0  -37.81830   144.99790
991        3       1.0     211.0  -37.82750   145.12320
3044       4       1.0    1504.0  -37.94400   145.00150
5305       2       2.0       0.0  -37.81980   145.00500
4043       2       2.0       0.0  -37.81610   145.10980
3897       3       1.0     764.0  -37.88140   145.05830
4716       2       2.0       0.0  -37.84310   144.94030
1316       3       1.0     216.0  -37.77460   144.96970
6431       4       2.0     700.0  -37.73260   145.08810
11669      3       1.0     968.0  -37.88523   145.28553
11571      2       1.0     170.0  -37.83658   144.86199
8298       4       3.0     697.0  -37.70100   144.99930
1900       2       1.0     156.0  -37.78920   144.99990
11472      1       1.0      80.0  -37.99825   145.08696
9338       3       2.0     600.0  -37.57686   144.71023
9510       3       1.0     118.0  -37.81351   144.98804
6023       5       2.0     661.0  -37.76510   144.82410
2960       4       2.0     453.0  -37.70160   144.89740
4729       2       1.0      90.0  -37.83570   144.93760
4996       3       1.0     495.0  -37.75210   145.01140

[4647 rows x 5 columns]

In [53]:
train_y

10385    1060000.0
5805      390000.0
8488      502000.0
6672     1055000.0
776      1900000.0
1637     1587500.0
5991      607000.0
10582     920000.0
1352      880000.0
8732     1275000.0
7736     1250000.0
4365      450000.0
8581     1005000.0
10690     735000.0
5239      784000.0
10741     373500.0
8613     1100000.0
5342      905000.0
7285      593000.0
419      1365000.0
2710      711000.0
7424     1250000.0
9631      865000.0
5864     1950000.0
3403      785000.0
1212     1845000.0
10252     500000.0
6074      480000.0
1459      970000.0
3996      483000.0
           ...
1391      521500.0
3648     3650000.0
168       678000.0
4531      815500.0
3396     2600000.0
3719      275000.0
9323      644000.0
9845     1020000.0
3948      470000.0
11866    1440000.0
5301      439000.0
991       775000.0
3044     2600000.0
5305     1040000.0
4043      725000.0
3897     1650000.0
4716      725000.0
1316     1261000.0
6431      895000.0
11669     740000.0
11571     510000.0
8298      770000.0
1900     1450000.0
11472     503750.0
9338      410000.0
9510     1875000.0
6023      605000.0
2960      709000.0
4729     1000000.0
4996      890000.0
Name: Price, Length: 4647, dtype: float64

In [54]:
melbourne_model=DecisionTreeRegressor()

In [55]:
melbourne_model

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [56]:
melbourne_model.fit(train_X,train_y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [57]:
# get predicted prices on validation data
val_predictions = melbourne_model.predict(val_X)

In [58]:
val_predictions

array([ 900000.,  696750., 1130000., ...,  240000., 1110000., 1045000.])

In [59]:
val_y

4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
3649      551000.0
5473      945000.0
1682     2400000.0
11114    1200000.0
439       850000.0
11493     710000.0
3900     1782500.0
4962      910000.0
6242     1650000.0
1032      765000.0
7714      577000.0
5024      875000.0
2575     1600000.0
6515     1010000.0
453       950000.0
1959     1000000.0
7928     2500000.0
1643     2200000.0
1361      820000.0
10652    1300000.0
11402     705000.0
4636      790000.0
10261     886000.0
8889     1205000.0
5208      340000.0
           ...
6716     1520000.0
2463     1500000.0
2723      740000.0
7532     1292000.0
141       520000.0
8820      500000.0
1995      451000.0
9463      755000.0
382      1710000.0
5926      950000.0
3746      349000.0
3964      570000.0
3541     1234500.0
2496      846000.0
8370      485000.0
7688      835000.0
6559      380000.0
3345     1210000.0
1404      810000.0
10664    1398000.0
6701      767000.0
3361      890000.0
577      2450000.0
7254      545000.0
8058      930000.0
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64

In [60]:
mean_absolute_error(val_y, val_predictions)

274827.30858618463